# NumPy 数组

In [1]:
import numpy as np

## 创建数组

### 从已有数组创建数组

In [2]:
np.array([1, 3, 2, 5, 4])

array([1, 3, 2, 5, 4])

In [3]:
np.array([3.14, 2, 6])

array([3.14, 2.  , 6.  ])

In [4]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### 从头创建数组

In [6]:
np.zeros(9, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((2, 5), dtype=np.float16)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float16)

In [8]:
np.full((3, 4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0, 14, 2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [10]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

### 随机数数组

In [11]:
np.random.seed(1)

In [12]:
np.random.random((2, 3))

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

In [13]:
np.random.randint(0, 4, (2, 4))

array([[0, 3, 1, 0],
       [2, 1, 2, 0]])

In [14]:
np.random.uniform(2, 6, (3, 4))

array([[3.67677806, 4.740878  , 2.817809  , 5.51246975],
       [2.10955037, 4.68187004, 3.66921921, 4.23475931],
       [2.56154775, 2.79240596, 5.20297827, 5.8730463 ]])

In [15]:
np.random.choice(np.arange(10), size=7)

array([6, 9, 1, 0, 1, 8, 8])

In [16]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([7, 2, 0, 4, 1, 5, 9, 6, 8, 3])

In [17]:
np.random.normal(0, 1, (2, 3))

array([[ 1.14194252, -1.12959516, -0.85005238],
       [ 0.96082   , -0.21741818,  0.15851488]])

In [18]:
rand = np.random.RandomState(10)
rand.random(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.empty(6)

array([1.14194252, 1.12959516, 0.85005238, 0.96082   , 0.21741818,
       0.15851488])

## 数组的类型

In [21]:
np.zeros(10, dtype='int16')
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [22]:
arr = np.random.randint(10, size=(2, 4))

In [23]:
arr.dtype

dtype('int32')

In [24]:
arr = np.random.randint(10, size=(2, 4))
arr.astype(np.float32)

array([[9., 3., 6., 8.],
       [0., 2., 7., 7.]], dtype=float32)

In [25]:
arr

array([[9, 3, 6, 8],
       [0, 2, 7, 7]])