# 数组的聚合与排序

In [1]:
import numpy as np

## 聚合

In [2]:
rand = np.random.RandomState(5)
a1 = rand.randint(0, 10, 10)
np.mean(a1)

4.3

In [3]:
big_array = rand.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

116 ms ± 2.43 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.37 ms ± 8.87 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
a1.std()

3.257299494980466

In [5]:
np.any(a1 == 10)

False

In [6]:
a2 = np.arange(12).reshape((3, 4))
a2.sum(axis=1)

array([ 6, 22, 38])

## 排序

In [7]:
a3 = rand.randint(0, 10, 8)
np.sort(a3)

array([2, 7, 7, 8, 8, 8, 9, 9])

In [8]:
np.argsort(a3)

array([3, 1, 5, 0, 2, 6, 4, 7], dtype=int32)

In [9]:
a3[np.argsort(a3)]

array([2, 7, 7, 8, 8, 8, 9, 9])

In [10]:
a4 = rand.randint(0, 10, (3, 4))
np.sort(a4, axis=1)

array([[0, 1, 7, 9],
       [0, 1, 4, 7],
       [0, 3, 6, 8]])

In [11]:
x1 = np.array([0, 2, 0, 1, 3, 2])
x2 = np.array([7, 8, 6, 6, 7, 7])
x3 = np.array([3, 3, 3, 4, 4, 3])
# sort by x3, then sort by x1, then sort by x2
np.lexsort((x2, x1, x3))

array([2, 0, 5, 1, 3, 4], dtype=int32)

In [12]:
np.partition(a1, 3)

array([0, 0, 0, 3, 6, 8, 4, 7, 6, 9])