# 数组的索引和切片

In [1]:
import numpy as np

## 数组的索引

In [2]:
a1 = np.arange(10)
print(a1[0], a1[4], a1[-2])

0 4 8


In [3]:
a2 = np.arange(12).reshape((3, 4))
print(a2)
print(a2[0, 0], a2[2, 1], a2[-3, -1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 9 3


In [4]:
a2[2, 1] = 23
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8, 23, 10, 11]])

In [5]:
a1[0] = 10.55
a1

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

## 数组的切片

In [6]:
print(a1[4:7])
print(a1[:5:-1])
print(a1[6::-2])

[4 5 6]
[9 8 7 6]
[ 6  4  2 10]


In [7]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8, 23, 10, 11]])

In [8]:
a2[:2, :3]  # slice to line, slice to col

array([[0, 1, 2],
       [4, 5, 6]])

In [9]:
a2[1:3, ::2]

array([[ 4,  6],
       [ 8, 10]])

In [10]:
a2[:, 0]

array([0, 4, 8])

In [11]:
a2[0, :]  # equals to a2[0]

array([0, 1, 2, 3])

In [12]:
a3 = np.arange(3 * 4 * 5).reshape((3, 4, 5))
a3[..., -1]  # equals to a3[:, :, -1]

array([[ 4,  9, 14, 19],
       [24, 29, 34, 39],
       [44, 49, 54, 59]])

In [13]:
a1[:, np.newaxis][:3]

array([[10],
       [ 1],
       [ 2]])

In [14]:
a1[np.newaxis, :, np.newaxis, np.newaxis][0, :, 0, 0]

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

## 数组索引

### 使用数组索引

In [15]:
a1[[0, 1, 2, 4, 8, -1]]

array([10,  1,  2,  4,  8,  9])

In [16]:
ind1 = np.array([[0, 1], [5, 8]])
a1[ind1]

array([[10,  1],
       [ 5,  8]])

In [17]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8, 23, 10, 11]])

In [18]:
a2[[1, 2, 2], [0, 1, 3]]

array([ 4, 23, 11])

In [19]:
a2[1, :-1]

array([4, 5, 6])

In [20]:
a2[1:, [0, -1]]

array([[ 4,  7],
       [ 8, 11]])

### 数组索引与修改值

In [21]:
a1[0:5] = 20
a1

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [22]:
a1[0:5] //= 4
a1

array([5, 5, 5, 5, 5, 5, 6, 7, 8, 9])

In [23]:
a1[[9, -1]] = [12, 13]
a1

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8, 13])

In [24]:
a1[[0, 0, 0, 0]] -= 10
a1

array([-5,  5,  5,  5,  5,  5,  6,  7,  8, 13])