# 通用函数

In [1]:
import numpy as np

## 通用函数的概念

In [2]:
def reciprocal(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [3]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit reciprocal(big_array)

2.37 s ± 38.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
small_array = np.random.randint(1, 10, size=5)
print(reciprocal(small_array))
print(1.0 / (small_array))

[0.14285714 0.5        0.125      0.25       0.16666667]
[0.14285714 0.5        0.125      0.25       0.16666667]


In [5]:
%timeit (1.0 / big_array)

3.07 ms ± 168 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## 使用通用函数

In [6]:
a1 = np.arange(5)
print('a1 + 5  =', a1 + 5)
print('a1 // 2 =', a1 // 2)
print('a1 ** 2 =', a1 ** 2)
print('-a1     =', -a1)

a1 + 5  = [5 6 7 8 9]
a1 // 2 = [0 0 1 1 2]
a1 ** 2 = [ 0  1  4  9 16]
-a1     = [ 0 -1 -2 -3 -4]


In [7]:
-(0.5 * a1 + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25, -9.  ])

In [8]:
np.add(a1, 5)

array([5, 6, 7, 8, 9])

In [9]:
a2 = np.array([3-4j, 4-3j, -2, -5j])
np.abs(a2)

array([5., 5., 2., 5.])

In [10]:
theta = np.linspace(0, np.pi, 3)
print('theta      :', theta)
print('sin(theta) :', np.sin(theta))
print('tan(theta) :', np.tan(theta))

theta      : [0.         1.57079633 3.14159265]
sin(theta) : [0.0000000e+00 1.0000000e+00 1.2246468e-16]
tan(theta) : [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [11]:
a3 = np.arange(1, 4)
print('a5     :', a3)
print('e^(a3) :', np.exp(a3))
print('2^(a3) :', np.exp2(a3))
print('3^(a3) :', np.power(3, a3))

a5     : [1 2 3]
e^(a3) : [ 2.71828183  7.3890561  20.08553692]
2^(a3) : [2. 4. 8.]
3^(a3) : [ 3  9 27]


In [12]:
a4 = np.array([1, 2, 4, 10])
print('a4        :', a4)
print('ln(a4)    :', np.log(a4))
print('log2(a4)  :', np.log2(a4))
print('log10(a4) :', np.log10(a4))

a4        : [ 1  2  4 10]
ln(a4)    : [0.         0.69314718 1.38629436 2.30258509]
log2(a4)  : [0.         1.         2.         3.32192809]
log10(a4) : [0.         0.30103    0.60205999 1.        ]


In [13]:
a5 = np.array([0, 0.001, 0.01, 0.1])
print('exp(a5) - 1 (bad) :', np.exp(a5) - 1)
print('exp(a5) - 1 (good):', np.expm1(a5))
print('ln(1 + a5)  (bad) :', np.log(a5 + 1))
print('ln(1 + a5)  (good):', np.log1p(a5))

exp(a5) - 1 (bad) : [0.         0.0010005  0.01005017 0.10517092]
exp(a5) - 1 (good): [0.         0.0010005  0.01005017 0.10517092]
ln(1 + a5)  (bad) : [0.         0.0009995  0.00995033 0.09531018]
ln(1 + a5)  (good): [0.         0.0009995  0.00995033 0.09531018]


In [14]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [15]:
a6 = np.arange(6).reshape((2, 3))
2 ** a6

array([[ 1,  2,  4],
       [ 8, 16, 32]], dtype=int32)

## 通用函数与布尔运算

In [16]:
a1 % 2 == 1

array([False,  True, False,  True, False])

In [17]:
(a1 > 1) & (a1 % 2 == 1)

array([False, False, False,  True, False])

In [18]:
a9 = np.random.RandomState(1).randint(0, 9, (10,))
a9[a9 % 2 == 0]

array([8, 0, 0, 6, 2, 4])

In [19]:
np.where(a9 % 2 == 0)

(array([1, 3, 4, 7, 8, 9], dtype=int32),)

## 通用函数的参数

In [20]:
a7 = np.empty(4)
np.multiply(a4, 2, out=a7)
a7

array([ 2.,  4.,  8., 20.])

In [21]:
a8 = np.ones(8)
np.add(a7, 3, out=a8[::2])
a8

array([ 5.,  1.,  7.,  1., 11.,  1., 23.,  1.])

In [22]:
np.multiply.reduce(a8)

8855.0

In [23]:
np.add.accumulate(a9)

array([ 5, 13, 18, 18, 18, 19, 26, 32, 34, 38], dtype=int32)

In [24]:
np.multiply.outer(a2, a7)

array([[  6.  -8.j,  12. -16.j,  24. -32.j,  60. -80.j],
       [  8.  -6.j,  16. -12.j,  32. -24.j,  80. -60.j],
       [ -4.  +0.j,  -8.  +0.j, -16.  +0.j, -40.  +0.j],
       [  0. -10.j,   0. -20.j,   0. -40.j,   0.-100.j]])

In [25]:
a_cnt = np.zeros(5)
a_rnd = np.random.RandomState(1).randint(0, 5, 10000)
np.add.at(a_cnt, a_rnd, 1)
a_cnt

array([2024., 1933., 2028., 2013., 2002.])

## 广播规则

In [26]:
x1 = np.array([1, 2, 3])
x2 = np.array([5, 4, 5])
x1 + x2

array([6, 6, 8])

In [27]:
x2 + 4

array([9, 8, 9])

In [28]:
y1 = np.full((3, 3), 2)
x1 + y1

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [29]:
x3 = x1[:, np.newaxis]
x1 + x3

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [30]:
x4, y4 = np.ones((3, 2)), np.ones((3,))
try:
    x4 + y4
except Exception as e:
    print(e.__class__, e)

<class 'ValueError'> operands could not be broadcast together with shapes (3,2) (3,) 
