# 数组变形、拼接与分裂

In [1]:
import numpy as np

## 数组的基本属性

In [2]:
np.random.seed(0)

In [3]:
a3 = np.random.randint(10, size=(3, 4, 5))
print('a3 ndim  :', a3.ndim)
print('a3 shape :', a3.shape)
print('a3 size  :', a3.size)

a3 ndim  : 3
a3 shape : (3, 4, 5)
a3 size  : 60


In [4]:
print('a3 dtype :', a3.dtype)

a3 dtype : int32


In [5]:
print('itemsize :', a3.itemsize, 'bytes')
print('nbytes :', a3.nbytes, 'bytes')

itemsize : 4 bytes
nbytes : 240 bytes


In [6]:
a1 = np.random.randint(10, size=10)
a1.nbytes

40

In [7]:
import sys, random
l3 = [random.randint(0, 9) for _ in range(10)]
sys.getsizeof(l3)

92

## 数组的变形

### 基本变形

In [8]:
m1 = np.arange(1, 10).reshape((3, 3))
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
np.arange(10).reshape((2, -1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
m1.shape = (-1)
m1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 转置

In [11]:
m2 = np.arange(6).reshape((2, 3))
m2

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
m2.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [13]:
m3 = np.arange(12).reshape((2, 3, 2))
m3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [14]:
m3.transpose()

array([[[ 0,  6],
        [ 2,  8],
        [ 4, 10]],

       [[ 1,  7],
        [ 3,  9],
        [ 5, 11]]])

In [15]:
m3.transpose((2, 0, 1)).shape

(2, 2, 3)

In [16]:
m2_T = m2.transpose()
m2_T[0] = 100
m2

array([[100,   1,   2],
       [100,   4,   5]])

### 变形与维度转换

In [17]:
a4 = np.array([[[1, 2, 3], [4, 5, 6]]])
a4.flatten()

array([1, 2, 3, 4, 5, 6])

In [18]:
a4.ravel()

array([1, 2, 3, 4, 5, 6])

In [19]:
a5 = np.array([[[[1], [2]], [[3], [4]]]])
a5.squeeze()

array([[1, 2],
       [3, 4]])

In [20]:
m3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [21]:
m3.swapaxes(1, 2)

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

## 数组的拼接和分裂

### 数组的拼接

In [22]:
x1 = np.array([1, 2, 3])
y1 = np.array([3, 2, 1])
np.concatenate([x1, y1])

array([1, 2, 3, 3, 2, 1])

In [23]:
z1 = np.array([9, 19, 29])
np.concatenate([x1, y1, z1])

array([ 1,  2,  3,  3,  2,  1,  9, 19, 29])

In [24]:
m2 = np.arange(6).reshape((2, 3))
m2

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
np.concatenate([m2, m2], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [26]:
np.append(m2, x1)

array([0, 1, 2, 3, 4, 5, 1, 2, 3])

In [27]:
np.vstack([x1, m2])  # vertical

array([[1, 2, 3],
       [0, 1, 2],
       [3, 4, 5]])

In [28]:
y2 = np.array([[100], [200]])
np.hstack([m2, y2])  # horizontal

array([[  0,   1,   2, 100],
       [  3,   4,   5, 200]])

In [29]:
np.stack([m2, m2], axis=1)

array([[[0, 1, 2],
        [0, 1, 2]],

       [[3, 4, 5],
        [3, 4, 5]]])

### 数组的分裂

In [30]:
a6 = [1, 2, 3, 4, 4, 3, 2, 1]
sub1, sub2, sub3 = np.split(a6, [3, 5])
print(sub1, sub2, sub3)

[1 2 3] [4 4] [3 2 1]


In [31]:
sub4, sub5, sub6 = np.split(np.arange(12).reshape(2, -1), [1, 3], axis=1)
sub4

array([[0],
       [6]])

In [32]:
sub6

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [33]:
m3 = np.arange(16).reshape((4, 4))

In [34]:
upper, lower = np.vsplit(m3, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
